"""
@author: Zach Chartrand <zachartrand999@gmail.com>

Project Euler Problem 2: https://projecteuler.net/problem=2

Even Fibonacci numbers
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.
"""

even_fib = []
a, b = 0, 1
while a < 4e6:
    if a % 2 == 0:
        even_fib.append(a)
    a, b = b, a + b

print(sum(even_fib))
